name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnotify4
      - name: Install Publii
        run: |
          wget https://cdn.getpublii.com/Publii-0.45.2.deb
          sudo dpkg -i Publii-0.45.2.deb
      - name: Add Publii to PATH
        run: |
          PUB_PATH=$(find /usr -name Publii | head -n 1)
          if [ -n "$PUB_PATH" ]; then
            echo "export PATH=\"$PUB_PATH:\$PATH\"" >> $HOME/.bashrc
            source $HOME/.bashrc
          else
            echo "Publii not found."
          fi
      - name: Build Website
        run: |
          publii build
      - name: Deploy Website
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_MUSHROOM_022EF1703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "build" # Adjust based on your Publii configuration


